name: server-test
on:
  pull_request:
    branches:
      - main
jobs:
  server-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setting up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Installing modules
        working-directory: ./server
        run: npm install
      - name: Building the code
        working-directory: ./server
        run: npm run build
      - name: Running the server
        working-directory: ./server
        run: npm run start:silent
      - name: Running the test
        working-directory: ./server
        run: npm run test